name: Documentation

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  DotNet:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup DocFx
        run: |
          nuget install docfx.console -Version 2.58.9
      - name: Get DocFx Template
        run: |
          cd ./Docs
          git clone https://github.com/ovasquez/docfx-material.git material
      - name: Get DocFx Metadata
        run: |
          cd ./Docs
          .\..\docfx.console.2.58.9\tools\docfx metadata
      - name: Generate Documentation
        run: |
          cd ./Docs
          .\..\docfx.console.2.58.9\tools\docfx
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs/_site
          destination_dir: ./
  OpenAPI:
    needs: DotNet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get OpenAPI files
        id: getfiles
        run:  |
          FILES="$(find -type f -iname "*.yaml")"
          echo "::set-output name=file_list::$FILES"
      - name: Validate
        uses: mbowman100/swagger-validator-action@master
        with:
          files: ${{ steps.getfiles.outputs.file_list }}
      - name: Generate Pages
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: api_spec.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          destination_dir: OpenAPI
